### PR TITLE
Localization and documentation updates

### PR DESCRIPTION
**Pull request by Kostenkov-2021**
* Russian nvda.po and readme.md file has been added.
* Spanish nvda.po file has been fixed.

### CODE REVIEW

**Comment by javidominguez** [comment]
What was the problem with spanish nvda.po?

**Comment by Kostenkov-2021** [comment]
There was some mistakes in accordance between source text and translation. also, Sam two variables was there in incorrect view. E.g.{ratio}% but not %{ratio}. I think it it makes sense to check the translation templates and translations on other languages.Отправлено с iPhone10 марта 2024 г., в 22:39, Javi Dominguez ***@***.***> написал(а):﻿
What was the problem with spanish nvda.po?

**Comment by javidominguez** [comment]
1. In the case you tell me, the % sign is a mathematical sign that expresses a percentage. The variable {ratio} is a percentage, which is why it is followed by the % sign. The same thing happens on the other string: "The rectangle occupies {percentage}% of the screen"

2. With the msgstr you can do whatever you want, put it before or after the variable, {ratio}% or %{ratio}, or replace it with the equivalent sign in your language but if you change the msgid in the .po file without having changed the corresponding string in the source code, they will not match and therefore the message will not be translated. This happens with your modifications in the Spanish translation, those two messages are not translated when they are spoken. I guess not in Russian either because the msgid input message does not match the message in the source code. The message in the source code is correct, in English the % sign is written after the number.

3. I write code in English but my native language is Spanish. Let me take care of that language and you check those two messages in Russian, make sure they are indeed translated. Please revert the changes to spanish nvda.po and I will merge the PR with the Russian localization.

**Comment by javidominguez** [comment]
I'm going to close this. If you wish, you can open a new pull request with only the Russian localization.

**Pull request closed without merging**
